// FortunaPanel - Proxy Config Generator
// Generates and manages proxy config files (velocity.toml, BungeeCord config.yml)
// and configures backend servers for proxy forwarding

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const logger = require('../utils/logger');

// --- Velocity Config ---

function generateVelocityConfig(network, proxyServer, backendServers, options = {}) {
    const { maintenanceServers = new Set(), forcedHosts = {} } = options;
    const bindPort = proxyServer.config.port || 25577;
    const secret = network.forwardingSecret;

    // Filter out maintenance servers
    const activeBackends = backendServers.filter(b => !maintenanceServers.has(b.id));

    // Build server entries
    const serverEntries = [];
    const tryOrder = [];
    for (const backend of activeBackends) {
        const alias = network.backendAliases[backend.id] || backend.name;
        serverEntries.push(`${alias} = "127.0.0.1:${backend.config.port}"`);
        tryOrder.push(`"${alias}"`);
    }

    // Put default server first in try order
    if (network.defaultServer && network.backendAliases[network.defaultServer]) {
        const defaultAlias = network.backendAliases[network.defaultServer];
        const idx = tryOrder.indexOf(`"${defaultAlias}"`);
        if (idx > 0) {
            tryOrder.splice(idx, 1);
            tryOrder.unshift(`"${defaultAlias}"`);
        }
    }

    // Build forced-hosts entries
    const forcedHostEntries = Object.entries(forcedHosts)
        .map(([fqdn, aliases]) => `"${fqdn}" = [${aliases.map(a => `"${a}"`).join(', ')}]`)
        .join('\n');

    const config = `# Velocity Configuration
# Generated by FortunaPanel - Manual edits to [servers] will be overwritten on sync

bind = "0.0.0.0:${bindPort}"
motd = "\\u00a7aA Velocity Server"
show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "${network.forwardingMode || 'modern'}"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"

[servers]
${serverEntries.length > 0 ? serverEntries.join('\n') : '# No backend servers configured yet'}

try = [${tryOrder.join(', ')}]

[forced-hosts]
${forcedHostEntries || '# No forced hosts configured'}

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true

[query]
enabled = false
port = 25577
map = "Velocity"
show-plugins = false
`;

    const dir = proxyServer.config.directory;
    fs.writeFileSync(path.join(dir, 'velocity.toml'), config);
    fs.writeFileSync(path.join(dir, 'forwarding.secret'), secret);
    logger.info(`Generated velocity.toml for network ${network.name}`);
}

// --- BungeeCord Config ---

function generateBungeeConfig(network, proxyServer, backendServers, options = {}) {
    const { maintenanceServers = new Set(), forcedHosts = {} } = options;
    const bindPort = proxyServer.config.port || 25577;

    // Filter out maintenance servers
    const activeBackends = backendServers.filter(b => !maintenanceServers.has(b.id));

    // Build server entries
    const serverLines = [];
    const priorities = [];
    for (const backend of activeBackends) {
        const alias = network.backendAliases[backend.id] || backend.name;
        serverLines.push(`  ${alias}:`);
        serverLines.push(`    motd: '&1${alias}'`);
        serverLines.push(`    address: 127.0.0.1:${backend.config.port}`);
        serverLines.push(`    restricted: false`);
        priorities.push(alias);
    }

    // Put default server first
    if (network.defaultServer && network.backendAliases[network.defaultServer]) {
        const defaultAlias = network.backendAliases[network.defaultServer];
        const idx = priorities.indexOf(defaultAlias);
        if (idx > 0) {
            priorities.splice(idx, 1);
            priorities.unshift(defaultAlias);
        }
    }

    const fallback = priorities[0] || '';

    // Build forced_hosts YAML
    let forcedHostsYaml = '{}';
    const forcedHostEntries = Object.entries(forcedHosts);
    if (forcedHostEntries.length > 0) {
        forcedHostsYaml = '\n' + forcedHostEntries
            .map(([fqdn, aliases]) => `    ${fqdn}: ${aliases[0] || ''}`)
            .join('\n');
    }

    const config = `# BungeeCord Configuration
# Generated by FortunaPanel - Manual edits to servers section will be overwritten on sync
server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: true
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: true
ip_forward: true
disabled_commands: []
network_compression_threshold: 256
groups: {}
listeners:
- query_port: 25577
  motd: '&1A BungeeCord Proxy'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: ${forcedHostsYaml}
  ping_passthrough: false
  priorities:
${priorities.map(p => `  - ${p}`).join('\n') || '  # No servers configured'}
  bind_local_address: true
  host: 0.0.0.0:${bindPort}
  max_players: 500
  tab_size: 60
  force_default_server: false
  fallback_server: '${fallback}'
servers:
${serverLines.length > 0 ? serverLines.join('\n') : '  # No backend servers configured yet'}
connection_throttle: 4000
connection_throttle_limit: 3
stats: null
prevent_proxy_connections: false
`;

    const dir = proxyServer.config.directory;
    fs.writeFileSync(path.join(dir, 'config.yml'), config);
    logger.info(`Generated config.yml for network ${network.name}`);
}

// --- Backend Server Configuration ---

function configureBackendForVelocity(serverDir, forwardingSecret) {
    // Set server.properties online-mode=false
    setServerProperty(serverDir, 'online-mode', 'false');

    // Configure Paper for Velocity modern forwarding
    const paperConfigDir = path.join(serverDir, 'config');
    if (!fs.existsSync(paperConfigDir)) {
        fs.mkdirSync(paperConfigDir, { recursive: true });
    }

    const paperGlobal = path.join(paperConfigDir, 'paper-global.yml');
    const paperConfig = `# Paper Global Configuration
# Modified by FortunaPanel for Velocity proxy support
proxies:
  velocity:
    enabled: true
    online-mode: true
    secret: "${forwardingSecret}"
`;
    fs.writeFileSync(paperGlobal, paperConfig);
    logger.info(`Configured backend at ${serverDir} for Velocity forwarding`);
}

function configureBackendForBungee(serverDir) {
    // Set server.properties online-mode=false
    setServerProperty(serverDir, 'online-mode', 'false');

    // Set spigot.yml bungeecord: true
    const spigotPath = path.join(serverDir, 'spigot.yml');
    if (fs.existsSync(spigotPath)) {
        let content = fs.readFileSync(spigotPath, 'utf-8');
        content = content.replace(/bungeecord:\s*false/i, 'bungeecord: true');
        fs.writeFileSync(spigotPath, content);
    } else {
        fs.writeFileSync(spigotPath, 'settings:\n  bungeecord: true\n');
    }

    // Configure Paper if config exists
    const paperGlobal = path.join(serverDir, 'config', 'paper-global.yml');
    if (fs.existsSync(path.join(serverDir, 'config'))) {
        const paperConfig = `# Paper Global Configuration
# Modified by FortunaPanel for BungeeCord proxy support
proxies:
  bungee-cord:
    online-mode: true
`;
        fs.writeFileSync(paperGlobal, paperConfig);
    }

    logger.info(`Configured backend at ${serverDir} for BungeeCord forwarding`);
}

function resetBackendConfig(serverDir) {
    // Restore online-mode=true
    setServerProperty(serverDir, 'online-mode', 'true');

    // Reset spigot.yml bungeecord setting
    const spigotPath = path.join(serverDir, 'spigot.yml');
    if (fs.existsSync(spigotPath)) {
        let content = fs.readFileSync(spigotPath, 'utf-8');
        content = content.replace(/bungeecord:\s*true/i, 'bungeecord: false');
        fs.writeFileSync(spigotPath, content);
    }

    // Reset Paper proxy config
    const paperGlobal = path.join(serverDir, 'config', 'paper-global.yml');
    if (fs.existsSync(paperGlobal)) {
        const paperConfig = `# Paper Global Configuration
proxies:
  velocity:
    enabled: false
    online-mode: true
    secret: ""
  bungee-cord:
    online-mode: true
`;
        fs.writeFileSync(paperGlobal, paperConfig);
    }

    logger.info(`Reset backend config at ${serverDir}`);
}

// --- Helpers ---

function setServerProperty(serverDir, key, value) {
    const propsPath = path.join(serverDir, 'server.properties');
    if (!fs.existsSync(propsPath)) return;

    let content = fs.readFileSync(propsPath, 'utf-8');
    const regex = new RegExp(`^${key}=.*$`, 'm');
    if (regex.test(content)) {
        content = content.replace(regex, `${key}=${value}`);
    } else {
        content += `\n${key}=${value}\n`;
    }
    fs.writeFileSync(propsPath, content);
}

function generateForwardingSecret() {
    return crypto.randomBytes(32).toString('base64');
}

function readProxyConfig(proxyType, proxyDir) {
    if (proxyType === 'velocity') {
        const configPath = path.join(proxyDir, 'velocity.toml');
        if (fs.existsSync(configPath)) {
            return fs.readFileSync(configPath, 'utf-8');
        }
    } else if (proxyType === 'bungeecord') {
        const configPath = path.join(proxyDir, 'config.yml');
        if (fs.existsSync(configPath)) {
            return fs.readFileSync(configPath, 'utf-8');
        }
    }
    return null;
}

module.exports = {
    generateVelocityConfig,
    generateBungeeConfig,
    configureBackendForVelocity,
    configureBackendForBungee,
    resetBackendConfig,
    generateForwardingSecret,
    readProxyConfig
};
